### ISSUE TITLE
Orange Color looks boring

### ISSUE THREAD

**Issue by deadcoder0904** [Ajusa/lit#13]
Maybe its just me but the orange color kinda looks bad. It doesn't work with the background, makes it boring I guess. Maybe changing it to some dark contrast color would make the website look great. Also the links are hard to read bcz of the color contrast. Now I'm not a designer but I like beautiful designs & I think the framework is great but the color takes the appeal away. What do you guys think ?

**Comment by events-jonas-chrisw** [comment]
Juts change primary color before you compile it?

**Comment by deadcoder0904** [comment]
I know that, I was saying about the website. Maybe blue, green would look much more appealing. Maybe that's just me then who didn't like it. No problemo.

**Comment by Ajusa** [comment]
I went with an orangish color because of the name, lit. Probably not going to change it unless a significant number of people think it looks out of place
