### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by styfle** [Ajusa/lit#15]
The `package.json` says the name is `lit` but [npm](https://www.npmjs.com/package/lit) shows something different.

Can you deploy to npm so that other projects can include this as a dependency.
Also CDNs such as unpkg and jsdilvr can work without build tools with npm packages.
For an example, see [copee](https://github.com/styfle/copee#browser-esm-usage).

**Comment by MartinKolarik** [comment]
jsDelivr also supports GitHub so you can use https://cdn.jsdelivr.net/gh/Ajusa/lit@0.1/dist/lit.css even now.

**Comment by Ajusa** [comment]
Okay, I will look into this. I'll also update the docs to use a CDN link for getting started. Thanks!

**Comment by Ajusa** [comment]
I published to npm, with the URL being [this](https://www.npmjs.com/package/@ajusa/lit)

Let me know if I need to do anything else!
