### ISSUE TITLE
Grid system with numbers?

### ISSUE THREAD

**Issue by Mark-Creeten** [Ajusa/lit#17]
In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier “B&W?” may be written as “B\&W\?” or “B\26 W\3F”.

**Comment by Ajusa** [comment]
What is the issue exactly? The numbers used in the grid are escaped the same way your last line describes, making it compliant

**Comment by Mark-Creeten** [comment]
when people are learning CSS, one of the first lessons would be, don't use number, it does not work for classes & ID's.
With your'e grid system class naming convention, you give the idea it is allowed to use numbers.
to make it work one has to do do a number converting in CSS, thats not common to do.
would it not be better to have "col-1" or "span1 col" etc..?

**Comment by Ajusa** [comment]
You are correct about it not being common, but I think that is why lit is so easy to use. With skeleton's grid, you had to type out what number you wanted, in full English. I think lit handles that problem beautifully.

I understand your concern, but I would hope that someone would look at the source before assuming such a thing. Do you think I should add a note about this on the docs?

**Comment by Mark-Creeten** [comment]
most of your'e downloads will be from people how do not look in to the source, so maybe yes, add a note for those people.
I like you your approach off writing plain English, but people like me will get that "huh" feeling when they see those numbers as classes. 
You can close this, as it is not a real breaking issue.

**Comment by Ajusa** [comment]
Okay, thanks for understanding. I will include a note in the docs.

It isn't widely used, so I can see why people might get confused
