### ISSUE TITLE
Add checkbox and radio button

### ISSUE THREAD

**Issue by daynox** [Ajusa/lit#2]
Hi, you did a very great job!
Can you add some simple styles to checkbox and radio button?

Thx :)

**Comment by Ajusa** [comment]
Hey daynox,
Glad you hear you liked it! Unfortunately, I am not planning on adding checkbox and radio button styles right now. They tend to be rather large and would probably double the size of lit.

If I find a way of adding styles without doing some crazy CSS stuff with labels, I'll be sure to add them in!

In the meantime, I recommend checking out [this](https://codepen.io/Havock94/pen/XKmMKv) for doing custom checkboxes and radios.

**Comment by daynox** [comment]
It is quite understandable, really a pity there is no light alternative to make this kind of change.
Thank you for taking the time and I'm looking forward for the future update :)

**Comment by Ajusa** [comment]
Yeah, I wish that CSS checkboxes were easy to style, and built into the spec.
