### ISSUE TITLE
The card example in the docs doesn't work because the w-100 class is missing from the img tag

### ISSUE THREAD

**Issue by EtienneDesticourt** [ajusa/lit#21]
Hi,

Cf title.

How it should be (actual html of the docs website): 
https://github.com/ajusa/lit/blob/430bd49875c1289402a30bf659a7c9d04d66ae24/docs/lit.html#L321

How it is (example), the class="w-100" is missing which makes the card not responsive:
https://github.com/ajusa/lit/blob/430bd49875c1289402a30bf659a7c9d04d66ae24/docs/lit.html#L339

Thank you for your work on this library, it's very nice and clean.

**Comment by ajusa** [comment]
Thanks for catching this! I'll fix it as soon as possible.

Also, does anyone know a way to have the code tag automatically generate from my HTML? I could probably set something up with Vue and JS, but if anyone knows a JS plugin that does this automatically, please tell me!

**Comment by ajusa** [comment]
fixed!
