### ISSUE TITLE
Can you remove Menu from index.html ?

### ISSUE THREAD

**Issue by deadcoder0904** [Ajusa/lit#7]
I don't think we need [Menu](https://github.com/Ajusa/lit/blob/master/index.html#L43) because when I was visiting I thought [Menu](https://github.com/Ajusa/lit/blob/master/index.html#L43) is some clickable link. Its a small thing upto you 😸

**Comment by Ajusa** [comment]
Yeah, I was debating over that too. Should I make it larger or something? Or rename it to components?

**Comment by deadcoder0904** [comment]
Yep you could make it as a headline (h3) or just completely remove it. It looks weird.

**Comment by Ajusa** [comment]
Yeah, I removed. With the documentation header right above, doesn't make much sense to have it in there.
